#pragma once

#define IDC_EDIT_QUERY 101
#define IDC_LIST_RESULTS 102
#define IDM_EXIT 10001

#define WM_APP_START_INDEX (WM_APP + 10)
#define WM_APP_INDEX_DONE (WM_APP + 11)
#define WM_APP_SEARCH_DONE (WM_APP + 12)
#define WM_APP_TRAYICON (WM_APP + 50)

#define IDS_APP_TITLE 200
#define IDS_TRAY_TIP 201
#define IDS_STATUS_INDEXING 202
#define IDS_STATUS_READY 203

#define IDT_SEARCH_DEBOUNCE 3001
#define HOTKEY_ID_TDS 1
